//==============================================================
// THIS FILE WAS GENERATED BY CODEGEN
// DO NOT EDIT THIS FILE DIRECTLY
// ANY CHANGES WILL BE OVERWRITTEN
//==============================================================

//============================import data types============================
import type {
  Application,
  ApplicationInput,
  CompanyResearch,
  CompanyResearchInput,
  InterviewNote,
  InterviewNoteInput,
  ResumeVersion,
  ResumeVersionInput
} from "../types";

//=apiBaseUrl is the base URL for the API, which can be configured via environment variables. It defaults to "http://localhost:4000" if not set. The request function is a helper that simplifies making API calls and handling responses, including error handling and JSON parsing. The exported functions correspond to various API endpoints for managing applications, interview notes, resume versions, and company research. Each function constructs the appropriate API path and HTTP method based on the operation being performed.

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || "http://localhost:4000";

//==============================API request helper function============================

async function request<T>(path: string, options?: RequestInit): Promise<T> {

//========apiBaseUrl + path===================================================
  const response = await fetch(`${apiBaseUrl}${path}`, {
    headers: {
      "Content-Type": "application/json",
      ...options?.headers
    },
    ...options
  });

//==============================Error handling and response parsing===========

  if (!response.ok) {
    const body = await response.json().catch(() => null);
    throw new Error(body?.message || "Request failed");
  }

  if (response.status === 204) {
    return undefined as T;
  }

//==============================Parse JSON response=============================

  return response.json() as Promise<T>;
}

//==============================API functions============================

//==============================Application APIs============================

export function getApplications() {
  return request<Application[]>("/api/applications");
}

export function getApplication(id: string) {
  return request<Application>(`/api/applications/${id}`);
}

export function createApplication(input: ApplicationInput) {
  return request<Application>("/api/applications", {
    method: "POST",
    body: JSON.stringify(input)
  });
}

export function updateApplication(id: string, input: Partial<ApplicationInput>) {
  return request<Application>(`/api/applications/${id}`, {
    method: "PUT",
    body: JSON.stringify(input)
  });
}

export function deleteApplication(id: string) {
  return request<void>(`/api/applications/${id}`, {
    method: "DELETE"
  });
}

//==============================Interview Note APIs============================

export function getInterviewNotes(applicationId: string) {
  return request<InterviewNote[]>(`/api/applications/${applicationId}/interview-notes`);
}

export function createInterviewNote(applicationId: string, input: InterviewNoteInput) {
  return request<InterviewNote>(`/api/applications/${applicationId}/interview-notes`, {
    method: "POST",
    body: JSON.stringify(input)
  });
}

export function updateInterviewNote(id: string, input: Partial<InterviewNoteInput>) {
  return request<InterviewNote>(`/api/interview-notes/${id}`, {
    method: "PUT",
    body: JSON.stringify(input)
  });
}

export function deleteInterviewNote(id: string) {
  return request<void>(`/api/interview-notes/${id}`, {
    method: "DELETE"
  });
}

//==============================Resume Version APIs============================

export function getResumeVersions() {
  return request<ResumeVersion[]>("/api/resume-versions");
}

export function getResumeVersion(id: string) {
  return request<ResumeVersion>(`/api/resume-versions/${id}`);
}

export function createResumeVersion(input: ResumeVersionInput) {
  return request<ResumeVersion>("/api/resume-versions", {
    method: "POST",
    body: JSON.stringify(input)
  });
}

export function updateResumeVersion(id: string, input: Partial<ResumeVersionInput>) {
  return request<ResumeVersion>(`/api/resume-versions/${id}`, {
    method: "PUT",
    body: JSON.stringify(input)
  });
}

export function deleteResumeVersion(id: string) {
  return request<void>(`/api/resume-versions/${id}`, {
    method: "DELETE"
  });
}

//==============================Company Research APIs============================

export function getCompanyResearch(applicationId: string) {
  return request<CompanyResearch | null>(`/api/applications/${applicationId}/company-research`);
}

export function createCompanyResearch(applicationId: string, input: CompanyResearchInput) {
  return request<CompanyResearch>(`/api/applications/${applicationId}/company-research`, {
    method: "POST",
    body: JSON.stringify(input)
  });
}

export function updateCompanyResearch(id: string, input: Partial<CompanyResearchInput>) {
  return request<CompanyResearch>(`/api/company-research/${id}`, {
    method: "PUT",
    body: JSON.stringify(input)
  });
}

export function deleteCompanyResearch(id: string) {
  return request<void>(`/api/company-research/${id}`, {
    method: "DELETE"
  });
}
